=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.3
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

module NinthBuilderDiscordBotAPIClient
  VERSION = '1.0.3'
end
