# -*- encoding: utf-8 -*-

=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.3
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "ninth_builder_discord_bot_api_client/version"

Gem::Specification.new do |s|
  s.name        = "ninth_builder_discord_bot_api_client"
  s.version     = NinthBuilderDiscordBotAPIClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["contact@example.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Discord Bot Cluster API Ruby Gem"
  s.description = "API documentation for the Discord Bot Cluster management system"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
