=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module NinthBuilderDiscordBotAPIClient
  class BuildsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Declare a new build
    # Declare a new build with URL, message, and filename
    # @param build_declaration [BuildDeclaration] 
    # @param [Hash] opts the optional parameters
    # @return [BuildResponse]
    def builds_post(build_declaration, opts = {})
      data, _status_code, _headers = builds_post_with_http_info(build_declaration, opts)
      data
    end

    # Declare a new build
    # Declare a new build with URL, message, and filename
    # @param build_declaration [BuildDeclaration] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(BuildResponse, Integer, Hash)>] BuildResponse data, response status code and response headers
    def builds_post_with_http_info(build_declaration, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BuildsApi.builds_post ...'
      end
      # verify the required parameter 'build_declaration' is set
      if @api_client.config.client_side_validation && build_declaration.nil?
        fail ArgumentError, "Missing the required parameter 'build_declaration' when calling BuildsApi.builds_post"
      end
      # resource path
      local_var_path = '/builds'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(build_declaration)

      # return_type
      return_type = opts[:debug_return_type] || 'BuildResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"BuildsApi.builds_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BuildsApi#builds_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
