=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module NinthBuilderDiscordBotAPIClient
  class GuildsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get all guilds
    # Retrieve a list of all Discord guild IDs the bot is connected to
    # @param [Hash] opts the optional parameters
    # @return [GetGuildsResponse]
    def guilds_get(opts = {})
      data, _status_code, _headers = guilds_get_with_http_info(opts)
      data
    end

    # Get all guilds
    # Retrieve a list of all Discord guild IDs the bot is connected to
    # @param [Hash] opts the optional parameters
    # @return [Array<(GetGuildsResponse, Integer, Hash)>] GetGuildsResponse data, response status code and response headers
    def guilds_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: GuildsApi.guilds_get ...'
      end
      # resource path
      local_var_path = '/guilds'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'GetGuildsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :operation => :"GuildsApi.guilds_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: GuildsApi#guilds_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
