=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NinthBuilderDiscordBotAPIClient::GeneralApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GeneralApi' do
  before do
    # run before each test
    @api_instance = NinthBuilderDiscordBotAPIClient::GeneralApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GeneralApi' do
    it 'should create an instance of GeneralApi' do
      expect(@api_instance).to be_instance_of(NinthBuilderDiscordBotAPIClient::GeneralApi)
    end
  end

  # unit tests for root_get
  # Get API information
  # Returns basic information about the API
  # @param [Hash] opts the optional parameters
  # @return [ApiInfo]
  describe 'root_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
