=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NinthBuilderDiscordBotAPIClient::GuildsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GuildsApi' do
  before do
    # run before each test
    @api_instance = NinthBuilderDiscordBotAPIClient::GuildsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GuildsApi' do
    it 'should create an instance of GuildsApi' do
      expect(@api_instance).to be_instance_of(NinthBuilderDiscordBotAPIClient::GuildsApi)
    end
  end

  # unit tests for guilds_get
  # Get all guilds
  # Retrieve a list of all Discord guild IDs the bot is connected to
  # @param [Hash] opts the optional parameters
  # @return [GetGuildsResponse]
  describe 'guilds_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
