=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NinthBuilderDiscordBotAPIClient::ShardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ShardsApi' do
  before do
    # run before each test
    @api_instance = NinthBuilderDiscordBotAPIClient::ShardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShardsApi' do
    it 'should create an instance of ShardsApi' do
      expect(@api_instance).to be_instance_of(NinthBuilderDiscordBotAPIClient::ShardsApi)
    end
  end

  # unit tests for shards_get
  # Get shard information
  # Retrieve information about all shards including status and statistics
  # @param [Hash] opts the optional parameters
  # @return [GetShardsResponse]
  describe 'shards_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for shards_presence_put
  # Set shard presences
  # Update the presence/activity status of all shards
  # @param set_shard_presences_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'shards_presence_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
