=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NinthBuilderDiscordBotAPIClient::BuildDeclaration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NinthBuilderDiscordBotAPIClient::BuildDeclaration do
  let(:instance) { NinthBuilderDiscordBotAPIClient::BuildDeclaration.new }

  describe 'test an instance of BuildDeclaration' do
    it 'should create an instance of BuildDeclaration' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NinthBuilderDiscordBotAPIClient::BuildDeclaration)
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
