=begin
#Discord Bot Cluster API

#API documentation for the Discord Bot Cluster management system

The version of the OpenAPI document: 1.0.1
Contact: contact@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'ninth_builder_discord_bot_api_client/api_client'
require 'ninth_builder_discord_bot_api_client/api_error'
require 'ninth_builder_discord_bot_api_client/version'
require 'ninth_builder_discord_bot_api_client/configuration'

# Models
require 'ninth_builder_discord_bot_api_client/models/api_info'
require 'ninth_builder_discord_bot_api_client/models/build_declaration'
require 'ninth_builder_discord_bot_api_client/models/build_response'
require 'ninth_builder_discord_bot_api_client/models/build_response_data'
require 'ninth_builder_discord_bot_api_client/models/error_response'
require 'ninth_builder_discord_bot_api_client/models/get_guilds_response'
require 'ninth_builder_discord_bot_api_client/models/get_shards_response'
require 'ninth_builder_discord_bot_api_client/models/set_shard_presences_request'
require 'ninth_builder_discord_bot_api_client/models/shard_info'
require 'ninth_builder_discord_bot_api_client/models/shard_stats'

# APIs
require 'ninth_builder_discord_bot_api_client/api/builds_api'
require 'ninth_builder_discord_bot_api_client/api/general_api'
require 'ninth_builder_discord_bot_api_client/api/guilds_api'
require 'ninth_builder_discord_bot_api_client/api/shards_api'

module NinthBuilderDiscordBotAPIClient
  class << self
    # Customize default settings for the SDK using block.
    #   NinthBuilderDiscordBotAPIClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
